disabled_rules:
  - trailing_whitespace

warning_threshold: 15

opt_in_rules:
  - attributes
  - closure_end_indentation
  - empty_count
  - explicit_init
  - first_where
  - force_unwrapping
  - missing_docs
  - object_literal
  - operator_usage_whitespace
  - private_outlet
  - redundant_nil_coalescing
  - switch_case_on_newline

class_delegate_protocol:
  severity: error

file_length:
  warning: 500

line_length:
  warning: 150
  error: 200

type_body_length:
  warning: 400
  error: 450

function_body_length:
  warning: 70
  error: 100

function_parameter_count:
  warning: 10
  error: 15

variable_name:
  min_length:
    warning: 1
    error: 0
  max_length:
    warning: 40
    error: 60

excluded:
  - Carthage
  - Pods
